import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "en" | "hi";

const translations = {
  en: {
    home: "Home",
    documents: "Documents",
    features: "Features",
    howItWorks: "How It Works",
    pricing: "Pricing",
    about: "About",
    contact: "Contact",
    downloadApp: "Download App",
    createDocument: "Create Document",
    english: "English",
    hindi: "हिंदी",
    back: "Back",
    backToHome: "Back to Home",
    selectPlan: "Select Plan",
    payPerPdf: "Pay Per PDF",
    monthlyPlan: "Monthly Plan",
    editDocument: "Edit Document",
    createPdf: "Create PDF",
    includedSubscription: "Included in Subscription",
    fileName: "File Name",
    enterFileName: "Enter file name",
    documentDetails: "Document Details",
    languages: "Languages",
    format: "Format",
    pdf: "PDF",
    court: "Court",
    category: "Category",
    disclaimer: "This template is for informational purposes. Verify accuracy with a qualified legal professional before use.",
    documentNotFound: "Document not found",
    noDocumentsFound: "No documents found",
    tryDifferentKeywords: "Try different keywords or browse by court",
    popularSearches: "Popular Searches",
    searchPlaceholder: "Search legal drafts, courts, documents...",
    browseTemplates: "Browse Templates",
    platformBadge: "India's Premier Legal Document Platform",
    heroTitle: "Create Legal Documents Faster, Smarter & Professionally",
    heroDescription: "Prepare, edit and download professional legal documents in Hindi and English with Legal Docs Maker — trusted by advocates, clerks, and law students across India.",
    exploreTemplates: "Explore Templates",
    templates: "Templates",
    pdfReady: "PDF Ready",
    easyEditing: "Easy Editing",
    selectDocument: "Select Document",
    courts: "Courts",
    searchDrafts: "Search legal drafts...",
    createPdfPrice: "Create PDF — ₹10",
    pdfGenerated: "PDF Generated",
    ready: "Ready",
    unlimitedPdfs: "Unlimited PDFs",
    districtCourtTemplates: "District Court Templates",
    highCourtTemplates: "High Court Templates",
    revenueCourtTemplates: "Revenue Court Templates",
    languageSupport: "Language Support",
    findDocument: "Find the Legal Document You Need",
    searchDescription: "Search across 200+ templates by court, category, or document name",
    noDocuments: "No documents found",
    popular: "Popular Searches",
    legalDocumentsByCourt: "Explore Legal Documents by Court",
    courtDescription: "Find the right format quickly from our organized legal document categories.",
    howDescription: "From template to professional PDF in minutes.",
    chooseDocument: "Choose a Document",
    chooseDocumentDescription: "Browse 200+ templates organized by court and category. Search by name or type.",
    enterDetails: "Enter Your Details",
    enterDetailsDescription: "Fill in the required fields — party names, dates, addresses, and case-specific information.",
    editReview: "Edit & Review",
    editReviewDescription: "Review the formatted document, make edits, and ensure everything is accurate before finalizing.",
    downloadPdf: "Download PDF",
    downloadPdfDescription: "Generate a professional, court-ready PDF document instantly and download it to your device.",
    bilingualTitle: "Legal Documents in Hindi & English",
    bilingualDescription: "Prepare and edit legal documents in the language you prefer. Switch between Hindi and English seamlessly — all templates are professionally formatted in both languages.",
    bilingualFeatures: "Professional formatting in both languages|Accurate Hindi legal terminology|Court-ready document formats|Easy language switching per document",
    featureHeading: "Everything You Need for Legal Drafting",
    featureDescription: "A complete toolkit designed for India's legal professionals and individuals.",
    easyCreation: "Easy Document Creation",
    easyCreationDescription: "Create professional legal documents in minutes with guided templates.",
    bilingualSupport: "Hindi & English Support",
    bilingualSupportDescription: "Full bilingual support for all templates and document formats.",
    professionalTemplates: "Professional Templates",
    professionalTemplatesDescription: "200+ court-ready templates reviewed for legal formatting standards.",
    editingTools: "Powerful Editing Tools",
    editingToolsDescription: "Inline editing with rich text formatting and field auto-fill.",
    saveEdit: "Save & Edit Documents",
    saveEditDescription: "Save drafts and return to edit them anytime from your account.",
    organizedCategories: "Organized Court Categories",
    organizedCategoriesDescription: "Documents organized by court type for fast, easy navigation.",
    fastSearch: "Fast Search",
    fastSearchDescription: "Instant search across all documents, courts, and categories.",
    mobileFriendly: "Mobile Friendly",
    mobileFriendlyDescription: "Full-featured mobile app on Android for legal drafting on the go.",
    professionalFormatting: "Professional Formatting",
    professionalFormattingDescription: "Correct legal indentation, margins, and typography by default.",
    premiumTemplates: "Premium Templates",
    premiumTemplatesDescription: "Exclusive high-quality templates for complex legal proceedings.",
    workflowHeading: "From Template to Professional PDF",
    workflowDescription: "Our streamlined workflow ensures every document is accurate, formatted, and court-ready.",
    simplePricing: "Simple & Transparent Pricing",
    pricingDescription: "Choose the plan that works best for you.",
    aboutTitle: "About Legal Docs Maker",
    contactTitle: "Contact Us",
    contactDescription: "Have a question or feedback? We'd love to hear from you.",
    emailSupport: "Email Support",
    jurisdiction: "Jurisdiction",
    fullName: "Full Name",
    emailAddress: "Email Address",
    phoneNumber: "Phone Number",
    subject: "Subject",
    yourMessage: "Your message...",
    sendMessage: "Send Message",
    messageSent: "Message Sent!",
    thankYou: "Your message has been sent successfully. We'll get back to you soon.",
    sendAnother: "Send another message",
    editor: "Document Editor",
    editorHint: "Edit your document in English, Hindi, or both languages.",
    bold: "Bold",
    italic: "Italic",
    underline: "Underline",
    alignLeft: "Align left",
    alignCenter: "Align center",
    alignRight: "Align right",
    fontSize: "Font size",
    lineSpacing: "Line spacing",
    bulletList: "Bullet list",
    undo: "Undo",
    redo: "Redo",
    downloadPdfAction: "Download PDF",
    pdfPrintHint: "Your browser will open the print dialog. Choose Save as PDF to download your document.",
    pdfReadyStatus: "PDF download is ready.",
  },
  hi: {
    home: "होम",
    documents: "दस्तावेज़",
    features: "सुविधाएँ",
    howItWorks: "यह कैसे काम करता है",
    pricing: "मूल्य निर्धारण",
    about: "हमारे बारे में",
    contact: "संपर्क",
    downloadApp: "ऐप डाउनलोड करें",
    createDocument: "दस्तावेज़ बनाएँ",
    english: "English",
    hindi: "हिंदी",
    back: "वापस",
    backToHome: "होम पर वापस जाएँ",
    selectPlan: "योजना चुनें",
    payPerPdf: "प्रति PDF भुगतान",
    monthlyPlan: "मासिक योजना",
    editDocument: "दस्तावेज़ संपादित करें",
    createPdf: "PDF बनाएँ",
    includedSubscription: "सदस्यता में शामिल",
    fileName: "फ़ाइल का नाम",
    enterFileName: "फ़ाइल का नाम दर्ज करें",
    documentDetails: "दस्तावेज़ विवरण",
    languages: "भाषाएँ",
    format: "प्रारूप",
    pdf: "PDF",
    court: "न्यायालय",
    category: "श्रेणी",
    disclaimer: "यह प्रारूप केवल सूचनात्मक उद्देश्यों के लिए है। उपयोग से पहले किसी योग्य कानूनी पेशेवर से सटीकता की पुष्टि करें।",
    documentNotFound: "दस्तावेज़ नहीं मिला",
    noDocumentsFound: "कोई दस्तावेज़ नहीं मिला",
    tryDifferentKeywords: "अलग शब्दों से खोजें या न्यायालय के अनुसार देखें",
    popularSearches: "लोकप्रिय खोजें",
    searchPlaceholder: "कानूनी प्रारूप, न्यायालय, दस्तावेज़ खोजें...",
    browseTemplates: "प्रारूप देखें",
    platformBadge: "भारत का प्रमुख कानूनी दस्तावेज़ प्लेटफ़ॉर्म",
    heroTitle: "कानूनी दस्तावेज़ बनाएँ तेज़ी से, समझदारी से और पेशेवर तरीके से",
    heroDescription: "Legal Docs Maker के साथ हिंदी और अंग्रेज़ी में पेशेवर कानूनी दस्तावेज़ तैयार, संपादित और डाउनलोड करें — अधिवक्ताओं, क्लर्कों और विधि छात्रों का भरोसेमंद प्लेटफ़ॉर्म।",
    exploreTemplates: "प्रारूप देखें",
    templates: "प्रारूप",
    pdfReady: "PDF तैयार",
    easyEditing: "आसान संपादन",
    selectDocument: "दस्तावेज़ चुनें",
    courts: "न्यायालय",
    searchDrafts: "कानूनी प्रारूप खोजें...",
    createPdfPrice: "PDF बनाएँ — ₹10",
    pdfGenerated: "PDF तैयार है",
    ready: "तैयार",
    unlimitedPdfs: "असीमित PDF",
    districtCourtTemplates: "जिला न्यायालय प्रारूप",
    highCourtTemplates: "उच्च न्यायालय प्रारूप",
    revenueCourtTemplates: "राजस्व न्यायालय प्रारूप",
    languageSupport: "भाषा सहायता",
    findDocument: "अपना कानूनी दस्तावेज़ खोजें",
    searchDescription: "न्यायालय, श्रेणी या दस्तावेज़ के नाम से 200+ प्रारूप खोजें",
    noDocuments: "कोई दस्तावेज़ नहीं मिला",
    popular: "लोकप्रिय खोजें",
    legalDocumentsByCourt: "न्यायालय के अनुसार कानूनी दस्तावेज़ देखें",
    courtDescription: "हमारी व्यवस्थित कानूनी दस्तावेज़ श्रेणियों से सही प्रारूप जल्दी खोजें।",
    howDescription: "प्रारूप से पेशेवर PDF तक कुछ ही मिनटों में।",
    chooseDocument: "दस्तावेज़ चुनें",
    chooseDocumentDescription: "न्यायालय और श्रेणी के अनुसार 200+ प्रारूप देखें। नाम या प्रकार से खोजें।",
    enterDetails: "अपना विवरण दर्ज करें",
    enterDetailsDescription: "पक्षकारों के नाम, तारीख, पते और मामले की आवश्यक जानकारी भरें।",
    editReview: "संपादित करें और जाँचें",
    editReviewDescription: "प्रारूपित दस्तावेज़ जाँचें, संपादन करें और अंतिम रूप देने से पहले सटीकता सुनिश्चित करें।",
    downloadPdf: "PDF डाउनलोड करें",
    downloadPdfDescription: "पेशेवर, न्यायालय के लिए तैयार PDF तुरंत बनाएँ और अपने डिवाइस पर डाउनलोड करें।",
    bilingualTitle: "हिंदी और अंग्रेज़ी में कानूनी दस्तावेज़",
    bilingualDescription: "अपनी पसंदीदा भाषा में कानूनी दस्तावेज़ तैयार और संपादित करें। हिंदी और अंग्रेज़ी के बीच आसानी से बदलें — सभी प्रारूप दोनों भाषाओं में पेशेवर रूप से तैयार हैं।",
    bilingualFeatures: "दोनों भाषाओं में पेशेवर प्रारूपण|सटीक हिंदी कानूनी शब्दावली|न्यायालय के लिए तैयार दस्तावेज़ प्रारूप|हर दस्तावेज़ में आसान भाषा परिवर्तन",
    featureHeading: "कानूनी प्रारूपण के लिए आवश्यक सभी सुविधाएँ",
    featureDescription: "भारत के कानूनी पेशेवरों और आम उपयोगकर्ताओं के लिए बनाया गया संपूर्ण टूलकिट।",
    easyCreation: "आसान दस्तावेज़ निर्माण",
    easyCreationDescription: "निर्देशित प्रारूपों से मिनटों में पेशेवर कानूनी दस्तावेज़ बनाएँ।",
    bilingualSupport: "हिंदी और अंग्रेज़ी सहायता",
    bilingualSupportDescription: "सभी प्रारूपों और दस्तावेज़ों के लिए पूर्ण द्विभाषी सहायता।",
    professionalTemplates: "पेशेवर प्रारूप",
    professionalTemplatesDescription: "कानूनी प्रारूपण मानकों के अनुसार जाँचे गए 200+ न्यायालय प्रारूप।",
    editingTools: "शक्तिशाली संपादन उपकरण",
    editingToolsDescription: "समृद्ध टेक्स्ट प्रारूपण और स्वचालित फ़ील्ड भरने के साथ संपादन।",
    saveEdit: "दस्तावेज़ सहेजें और संपादित करें",
    saveEditDescription: "ड्राफ्ट सहेजें और अपने खाते से कभी भी वापस आकर संपादित करें।",
    organizedCategories: "व्यवस्थित न्यायालय श्रेणियाँ",
    organizedCategoriesDescription: "तेज़ और आसान नेविगेशन के लिए न्यायालय के अनुसार दस्तावेज़ व्यवस्थित।",
    fastSearch: "तेज़ खोज",
    fastSearchDescription: "सभी दस्तावेज़ों, न्यायालयों और श्रेणियों में तुरंत खोजें।",
    mobileFriendly: "मोबाइल के अनुकूल",
    mobileFriendlyDescription: "चलते-फिरते कानूनी प्रारूपण के लिए Android पर पूर्ण सुविधा वाला ऐप।",
    professionalFormatting: "पेशेवर प्रारूपण",
    professionalFormattingDescription: "सही कानूनी इंडेंटेशन, मार्जिन और टाइपोग्राफी डिफ़ॉल्ट रूप से।",
    premiumTemplates: "प्रीमियम प्रारूप",
    premiumTemplatesDescription: "जटिल कानूनी कार्यवाही के लिए विशेष उच्च गुणवत्ता वाले प्रारूप।",
    workflowHeading: "प्रारूप से पेशेवर PDF तक",
    workflowDescription: "हमारा सरल कार्यप्रवाह हर दस्तावेज़ को सटीक, प्रारूपित और न्यायालय के लिए तैयार रखता है।",
    simplePricing: "सरल और पारदर्शी मूल्य निर्धारण",
    pricingDescription: "अपने लिए सबसे उपयुक्त योजना चुनें।",
    aboutTitle: "Legal Docs Maker के बारे में",
    contactTitle: "संपर्क करें",
    contactDescription: "कोई प्रश्न या सुझाव है? हमें आपसे सुनकर खुशी होगी।",
    emailSupport: "ईमेल सहायता",
    jurisdiction: "अधिकार क्षेत्र",
    fullName: "पूरा नाम",
    emailAddress: "ईमेल पता",
    phoneNumber: "फ़ोन नंबर",
    subject: "विषय",
    yourMessage: "आपका संदेश...",
    sendMessage: "संदेश भेजें",
    messageSent: "संदेश भेज दिया गया!",
    thankYou: "संपर्क करने के लिए धन्यवाद। हम 24 घंटे के भीतर उत्तर देंगे।",
    sendAnother: "एक और संदेश भेजें",
    editor: "दस्तावेज़ संपादक",
    editorHint: "अपने दस्तावेज़ को हिंदी, अंग्रेज़ी या दोनों भाषाओं में संपादित करें।",
    bold: "बोल्ड",
    italic: "इटैलिक",
    underline: "रेखांकित",
    alignLeft: "बाएँ संरेखित करें",
    alignCenter: "केंद्र में संरेखित करें",
    alignRight: "दाएँ संरेखित करें",
    fontSize: "अक्षर आकार",
    lineSpacing: "पंक्ति अंतर",
    bulletList: "बुलेट सूची",
    undo: "पूर्ववत करें",
    redo: "फिर से करें",
    downloadPdfAction: "PDF डाउनलोड करें",
    pdfPrintHint: "आपके ब्राउज़र में प्रिंट संवाद खुलेगा। दस्तावेज़ डाउनलोड करने के लिए PDF के रूप में सहेजें चुनें।",
    pdfReadyStatus: "PDF डाउनलोड के लिए तैयार है।",
  },
} as const;

type TranslationKey = {
  [Key in keyof typeof translations.en]: typeof translations.en[Key] extends string ? Key : never;
}[keyof typeof translations.en];
type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = window.localStorage.getItem("legal-docs-language");
    return saved === "hi" ? "hi" : "en";
  });

  useEffect(() => {
    window.localStorage.setItem("legal-docs-language", language);
    document.documentElement.lang = language === "hi" ? "hi" : "en";
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key: TranslationKey) => translations[language][key],
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}